apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/nfs-data"
      name: nfs-vol
    - mountPath: "/pv-data"
      name: pv
  volumes:
  - name: nfs-vol
    nfs:
      server: 192.168.56.10
      path: /srv/nfs
  - name: pv
    persistentVolumeClaim:
      claimName: pvc-pod
